#!/bin/bash

RESULTADOS="resultados_optimizacion.txt"
> $RESULTADOS 

echo "Iniciando Grid Search con ZCR en Hz..."

ALPHA0=2.1
LIM_VEU=30
LIM_SIL=100

for a1 in 8.1 8.2 8.3; do
    for a2 in 0.5 0.6 0.7; do
        for zcr in 2000 2500 3000 3500 4000; do
            
            echo -ne "Probando a1=$a1, a2=$a2, zcr=$zcr Hz...\t"
            SCORE=$(scripts/run_vad.sh -0 $ALPHA0 -1 $a1 -2 $a2 -l $LIM_SIL -p $LIM_VEU -z $zcr | grep TOTAL)
            echo "$SCORE"
            echo "$SCORE | a1=$a1, a2=$a2, zcr=$zcr" >> $RESULTADOS
        done
    done
done

echo "------------------------------------------------"
sort -nr $RESULTADOS | head -n 5